language: php

env:
  - DOCKER_COMPOSE_VERSION=1.23.2
  - DOCKER_USERNAME=Arkowsky
  - DOCKER_PASSWORD=test

before_install:
  - docker-compose -v
  - docker -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v

script:
  - docker-compose pull
  - docker-compose build
  - docker images
  - echo 'Tests...'

after_success:
  - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/skeleton-php-images
  - docker push $DOCKER_USERNAME/skeleton-php-images

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
#  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: chmod +x gcloud/deploy-prod.sh && gcloud/deploy-prod.sh
    skip_cleanup: true
    on:
      branch: master
#deploy:
#  - PUSH IMAGE